# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
#Spring DataSource
spring:
  datasource:
    hikari:
      connection-timeout: 60000
      idle-timeout: 60000
      max-lifetime: 180000
      maximum-pool-size: 10
    url: jdbc:postgresql://127.0.0.1/book_catalog
    username: ucorp
    password: ucorp
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
          order_inserts: true
    show-sql: true


  application:
    name: Simple Catalog Book Using Spring Boot
server:
  port: 8081
debug: false
app:
  welcome-text: Hello World from Belajar Spring boot Sampai Siap Kerja
  currency: IDR
  time-zone: Asia/Tokyo
logging:
  level:
    root: INFO 
    '[com.ucorp.catalog]': DEBUG
    '[com.ucorp.catalog.service.impl.BookServiceImpl]': DEBUG
#        hikari: Debug
#        catalog: DEBUG
#        service: DEBUG
#        aop: DEBUG
---
spring:
  config:
    activate:
      on-profile: development

---
spring:
  config:
    activate:
      on-profile: staging
app:
  welcome-text: Hello World from Staging
  currency: JPY

---
spring:
  config:
    activate:
      on-profile: production
app:
  welcome-text: ${WELCOME_TEXT}
  currency: ${CURRENCY}